### ISSUE TITLE
question: how to prevent disappearing funds?

### ISSUE THREAD

**Issue by immesys** [etherapis/etherapis#21]
Sorry to clutter the issues with a question, but I'm trying to become acquainted with the code and the idea. One thing has eluded me though. Say the provider gets an invocation from a consumer, and it receives the "cheque" (to follow the metaphor used in the readme). The provider can verify that the account has sufficient credits by inspecting the block chain, but how does it verify that the account will _still_ have sufficient credits by the time it cashes the cheque? Isn't there a race between the consumer closing the account and getting their funds back and the provider cashing the cheque? What if the provider is delayed a bit in cashing the cheque because of network outages or whatnot?

**Comment by karalabe** [comment]
Hey @immesys , that's a completely valid question :) The original hackathon code was quite limited so it did not have this feature (and we're still cleaning up the code since then, transitioning to the dashboard). 

The way we're solving this issue is that the provider of each service will (beside the price and payment model of the API), also specify the cancellation time (e.g. 1 hour). That would mean, that when a consumer unsubscribes, he needs to wait for this much time before remaining funds are released; and similarly, the provider has this much contingency to charge any pending payments.

**Comment by immesys** [comment]
OK, I think that's pretty much the only solution to the problem, even though it's not a strong guarantee I think it's the best you can get. Thanks for answering!
